name: 'Run Test'
description: 'Runs specific test, resolves the logs path, and uploads the logs'
inputs:
  test_set:
    description: "Name of the Test Set to run"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run All Tests
      run: |
        cd tests
        sipssert ${{ inputs.test_set }}
      shell: bash

    - name: Publish logs
      if: always()
      uses: ./sipssert/actions/Publish_Logs
      with:
        log_name: sipssert-${{ inputs.test_set }}-logs
