name: 'Run All Tests'
description: 'Runs all tests, resolves the logs path, and uploads the logs'
inputs: {}
runs:
  using: 'composite'
  steps:
    - name: Run All Tests
      run: |
        cd tests
        sudo sh -x ./run-all.sh
      shell: bash

    - name: Publish logs
      if: always()
      uses: ./sipssert/actions/Publish_Logs
