name: 'Checkout and Install SIPssert & Tests'
description: 'Checks out and installs the SIPssert & Tests repos'
inputs:
  sipssert-repo:
    description: 'SIPssert repository to checkout'
    required: false
    default: 'OpenSIPS/SIPssert'
  tests-repo:
    description: 'Tests repository to checkout'
    required: false
    default: ${{ github.repository }}
runs:
  using: 'composite'
  steps:
    - name: Checkout SIPssert repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.sipssert-repo }}
        path: sipssert

    - name: Install SIPssert requirements
      run: |
        sudo apt update && sudo apt install -y tcpdump
      shell: bash

    - name: Install SIPssert framework
      run: |
        cd sipssert
        python3 setup.py install --user clean
      shell: bash

    - name: Checkout Tests repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.tests-repo }}
        path: tests
