name: 'Run Tests'
description: 'Runs the tests in a specific directory, resolves the logs path, and uploads the logs'
inputs:
  config:
    description: "run.yml file"
    required: false
    default: run.yml
  tests:
    description: "tests to run"
    required: false
    default: ''
  directory:
    description: "tests directory"
    required: false
    default: 'tests'
runs:
  using: 'composite'
  steps:
    - name: Run All Tests
      run: |
        cd ${{ inputs.directory }}
        sipssert --junit-xml -c ${{ inputs.config }} ${{ inputs.tests }}
      shell: bash

    - name: Publish logs
      if: always()
      uses: ./sipssert/.github/actions/Publish_Logs
      with:
        log_name: sipssert-${{ inputs.tests }}-logs
        directory: ${{ inputs.directory }}
    
    - name: Print test summary
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
        check_name: 'SIPssert test report'
        report_paths: ${{ inputs.directory }}/logs/latest/report.xml
        annotate_only: true
        fail_on_failure: true

    - name: Print detail test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: 'SIPssert report: ${{ inputs.tests }}'
        path: ${{ inputs.directory }}/logs/latest/report.xml
        reporter: java-junit
        fail_on_error: false
        max-annotations: 0
