name: 'Checkout and Install SIPssert'
description: 'Checks out and installs the SIPssert repo'
inputs:
  sipssert-repo:
    description: 'SIPssert repository to checkout'
    required: false
    default: 'OpenSIPS/SIPssert'
runs:
  using: 'composite'
  steps:
    - name: Checkout SIPssert repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.sipssert-repo }}
        path: sipssert

    - name: Install SIPssert requirements
      run: |
        sudo apt update && sudo apt install -y tcpdump
        sudo chmod +s $(which tcpdump)
      shell: bash

    - name: Install SIPssert framework
      run: |
        cd sipssert
        python3 setup.py install --user clean
      shell: bash
