name: 'Read Job Matrix'
description: 'Read list of scenarious to run and output matrix.'
inputs: {}
outputs:
  matrix:
    description: "The job matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: 'composite'
  steps:
    - name: Read and parse YAML file
      id: set-matrix
      run: |
        echo "Reading YAML file to create matrix"
        MATRIX=$(python3 sipssert/actions/read_matrix.py tests/matrix.yml)
        echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT
      shell: bash
