name: Run OpenSIPS Conformance Tests

on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

    - name: Checkout Tests repo
      uses: actions/checkout@v4
      with:
        repository: OpenSIPS/sipssert-opensips-tests
        path: tests

    - name: Read and parse YAML file
      id: set-matrix
      uses: OpenSIPS/SIPssert/.github/actions/Set_Matrix@main

  test:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    runs-on: ${{ matrix.os }}

    steps:

    - name: Prepare SIPssert
      uses: OpenSIPS/SIPssert/.github/actions/Prepare_SIPssert@main
      with:
        sipssert-repo: ${{ github.repository }}
        tests-repo: OpenSIPS/sipssert-opensips-tests

    - name: Run Test
      uses: OpenSIPS/SIPssert/.github/actions/Run_Tests@main
      with:
        tests: ${{ matrix.tests }}
