name: Run OpenSIPS Conformance Tests

on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

    - name: Prepare SIPssert
      uses: OpenSIPS/SIPssert/actions/Prepare_SIPssert@main
      with:
        sipssert-repo: ${{ github.repository }}
        tests-repo: OpenSIPS/sipssert-opensips-tests

    - name: Read and parse YAML file
      id: set-matrix
      uses: ./sipssert/actions/Set_Matrix

  test:
    needs: setup-matrix
    strategy:
      matrix: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    runs-on: ${{ matrix.os }}

    steps:

    - name: Prepare SIPssert
      uses: OpenSIPS/SIPssert/actions/Prepare_SIPssert@main
      with:
        sipssert-repo: ${{ github.repository }}
        tests-repo: OpenSIPS/sipssert-opensips-tests

    - name: Run Test
      uses: ./sipssert/actions/Run_Test
      with:
        test_set: ${{ matrix.test_set }}
